title: Junghyeonee_Blog
description: Bigdata_Analysis
author: Yang Jung Hyun
avatar: /cute.jpg
email: 20202797@gm.hannam.ac.kr

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

paginate: 10

skin: daylight
# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
instagram:
  username: junghyeonee
  card: summary
logo: cute.jpg
social:
  name: junghyeonee
  links:
    - https://instagram.com/junghyeonee
    - https://github.com/junghyeonee
lang: en
remote_theme: ngzhio/jekyll-theme-hamilton
